<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>

    <!-- Root Namespace -->
    <RootNamespace>PPWCode.Host.Core</RootNamespace>

    <!-- nuget package -->
    <IsPackable>true</IsPackable>

    <!-- Stylecop -->
    <CodeAnalysisRuleSet>..\StyleCop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <!-- Castle Windsor -->
    <PackageReference Include="Castle.Windsor" Version="5.1.1" />
    <PackageReference Include="Castle.Windsor.Extensions.DependencyInjection" Version="5.1.1" />
  </ItemGroup>

  <Choose>
    <When Condition=" '$(TargetFramework)' == 'net8.0' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.*" />
      </ItemGroup>
    </When>
  </Choose>
</Project>
